/* Widget de suporte: isolado em Shadow DOM e sem dependências. */
(function () {
  "use strict";
  var script = document.currentScript;
  if (!script) return;
  var data = script.dataset || {};
  var endpoint = String(data.endpoint || "").replace(/\/$/, "");
  var anonKey = data.anonKey || "";
  var title = data.titulo || "Fale com a gente";
  var color = data.cor || "#7C3AED";
  if (!endpoint) return;
  var rootHost = document.createElement("div"); rootHost.setAttribute("data-suporte-widget", "true");
  if (!rootHost.attachShadow) return;
  document.body.appendChild(rootHost);
  var root = rootHost.attachShadow({ mode: "open" });
  var style = document.createElement("style"); style.textContent = ":host{all:initial}*{box-sizing:border-box}[hidden]{display:none!important}.launcher{position:fixed;right:22px;bottom:22px;z-index:2147483000;width:58px;height:58px;border:0;border-radius:50%;background:" + color + ";color:#fff;box-shadow:0 8px 24px rgba(0,0,0,.22);font:700 25px system-ui;cursor:pointer}.launcher:focus,.close:focus,.send:focus,input:focus,textarea:focus{outline:3px solid rgba(255,255,255,.55);outline-offset:2px}.panel{position:fixed;right:22px;bottom:92px;z-index:2147483000;display:flex;flex-direction:column;width:min(370px,calc(100vw - 28px));height:min(590px,calc(100vh - 120px));overflow:hidden;border:1px solid #ddd6fe;border-radius:18px;background:#fff;color:#252230;box-shadow:0 18px 55px rgba(25,15,40,.26);font:14px/1.45 system-ui,-apple-system,sans-serif}.head{display:flex;align-items:center;justify-content:space-between;padding:17px 18px;background:" + color + ";color:#fff}.head strong{font-size:15px}.head small{display:block;margin-top:2px;opacity:.8}.close{border:0;background:transparent;color:#fff;font-size:25px;line-height:1;cursor:pointer}.messages{display:flex;flex:1;flex-direction:column;gap:9px;overflow-y:auto;padding:16px;background:#faf9fd}.bubble{max-width:84%;white-space:pre-wrap;overflow-wrap:anywhere;border-radius:13px;padding:10px 12px}.bubble.bot{align-self:flex-start;background:#ece9f5}.bubble.user{align-self:flex-end;background:" + color + ";color:#fff}.bubble.note{align-self:center;max-width:95%;background:transparent;color:#716c7d;font-size:12px;text-align:center}.typing{color:#716c7d;font-size:12px;font-style:italic}.contact{display:grid;gap:7px;padding:12px 15px 0}.contact[hidden]{display:none}.form-label{color:#716c7d;font-size:12px}.contact input,.composer textarea{width:100%;border:1px solid #d9d3e7;border-radius:9px;padding:9px;background:#fff;color:#252230;font:inherit}.composer{display:flex;gap:8px;align-items:flex-end;padding:12px 15px 15px;border-top:1px solid #e8e4ef;background:#fff}.composer textarea{resize:none;min-height:42px;max-height:120px}.send{flex:0 0 auto;border:0;border-radius:9px;padding:10px 13px;background:" + color + ";color:#fff;font-weight:700;cursor:pointer}.send:disabled{opacity:.55;cursor:not-allowed}@media(max-width:480px){.launcher{right:14px;bottom:14px}.panel{right:14px;bottom:84px;width:calc(100vw - 28px);height:min(620px,calc(100vh - 105px))}"; root.appendChild(style);
  var button = document.createElement("button"); button.className = "launcher"; button.type = "button"; button.setAttribute("aria-label", title); button.textContent = "?"; root.appendChild(button);
  var panel = document.createElement("section"); panel.className = "panel"; panel.hidden = true; panel.setAttribute("aria-label", title);
  var head = document.createElement("header"); head.className = "head"; var headText = document.createElement("div"); var headTitle = document.createElement("strong"); headTitle.textContent = title; var headSub = document.createElement("small"); headSub.textContent = "Respondemos por aqui"; headText.appendChild(headTitle); headText.appendChild(headSub); var close = document.createElement("button"); close.className = "close"; close.type = "button"; close.setAttribute("aria-label", "Fechar atendimento"); close.textContent = "×"; head.appendChild(headText); head.appendChild(close); panel.appendChild(head);
  var messages = document.createElement("div"); messages.className = "messages"; messages.setAttribute("aria-live", "polite"); panel.appendChild(messages);
  var contact = document.createElement("div"); contact.className = "contact"; var contactLabel = document.createElement("label"); contactLabel.className = "form-label"; contactLabel.textContent = "Como podemos chamar você? (opcional)"; var contactInput = document.createElement("input"); contactInput.type = "text"; contactInput.maxLength = 120; contactInput.autocomplete = "name"; contactInput.placeholder = "Seu nome"; contact.appendChild(contactLabel); contact.appendChild(contactInput); panel.appendChild(contact);
  var composer = document.createElement("form"); composer.className = "composer"; var input = document.createElement("textarea"); input.rows = 1; input.maxLength = 2000; input.placeholder = "Digite sua mensagem…"; input.setAttribute("aria-label", "Mensagem"); var send = document.createElement("button"); send.className = "send"; send.type = "submit"; send.textContent = "Enviar"; composer.appendChild(input); composer.appendChild(send); panel.appendChild(composer); root.appendChild(panel);
  var storageKey = "suporte_conversa_id"; var ticketStorageKey = "suporte_ticket_aberto"; var conversationId = null; var ticketOpen = false; var poll = null; var historyBusy = false; var busy = false;
  try { conversationId = window.localStorage.getItem(storageKey); } catch (ignore) {}
  if (!conversationId) { try { conversationId = window.crypto && window.crypto.randomUUID ? window.crypto.randomUUID() : "c-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2); } catch (ignoreCrypto) { conversationId = "c-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2); } try { window.localStorage.setItem(storageKey, conversationId); } catch (ignoreSave) {} }
  try { ticketOpen = window.localStorage.getItem(ticketStorageKey) === "true"; } catch (ignoreTicket) {}
  function persistTicket(open) { ticketOpen = !!open; try { window.localStorage.setItem(ticketStorageKey, ticketOpen ? "true" : "false"); } catch (ignoreSaveTicket) {} }
  function addMessage(text, kind) { var bubble = document.createElement("div"); bubble.className = "bubble " + (kind || "bot"); bubble.textContent = String(text || ""); messages.appendChild(bubble); messages.scrollTop = messages.scrollHeight; return bubble; }
  function setTyping(visible) { var old = messages.querySelector(".typing"); if (old) old.remove(); if (visible) { var node = document.createElement("div"); node.className = "bubble note typing"; node.textContent = "digitando…"; messages.appendChild(node); messages.scrollTop = messages.scrollHeight; } }
  async function request(body) { var response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json", apikey: anonKey, Authorization: "Bearer " + anonKey }, body: JSON.stringify(body) }); var payload = null; try { payload = await response.json(); } catch (ignore) {} if (!response.ok) throw new Error(payload && (payload.erro || payload.error || payload.message) || "Não foi possível falar com o suporte."); return payload || {}; }
  function stopPolling() { if (poll) { window.clearInterval(poll); poll = null; } }
  async function history() { if (panel.hidden || historyBusy) return; historyBusy = true; try { var dataResult = await request({ acao: "historico", canal: "site", conversa_id: conversationId }); var items = Array.isArray(dataResult.mensagens) ? dataResult.mensagens : Array.isArray(dataResult) ? dataResult : []; if (items.length) persistTicket(true); items.forEach(function (item) { var marker = item.id || item.created_at || item.conteudo; var safeMarker = String(marker || "").replace(/[^a-zA-Z0-9_-]/g, ""); if (!marker || messages.querySelector('[data-message-id="' + safeMarker + '"]')) return; var bubble = addMessage(item.conteudo, "bot"); bubble.dataset.messageId = safeMarker; }); } catch (ignore) {} finally { historyBusy = false; } }
  function startPolling() { stopPolling(); if (!ticketOpen || panel.hidden) return; poll = window.setInterval(history, 8000); }
  async function submit(event) { event.preventDefault(); var text = input.value.trim(); if (!text || busy) return; busy = true; send.disabled = true; input.value = ""; addMessage(text, "user"); setTyping(true); var contactData = {}; if (contactInput.value.trim()) contactData.nome = contactInput.value.trim(); try { var result = await request({ acao: "mensagem", canal: "site", conversa_id: conversationId, mensagem: text, contato: contactData }); setTyping(false); if (result.resposta) addMessage(result.resposta, "bot"); if (result.escalou || result.ticket_id) { persistTicket(true); addMessage("Sua mensagem foi enviada à equipe. Em breve alguém continua o atendimento por aqui.", "note"); startPolling(); } } catch (error) { setTyping(false); addMessage(error.message || "Não foi possível enviar agora. Tente novamente.", "note"); } finally { busy = false; send.disabled = false; input.focus(); } }
  function open() { panel.hidden = false; button.setAttribute("aria-expanded", "true"); if (!messages.childNodes.length) addMessage("Olá! Como podemos ajudar?", "bot"); input.focus(); history(); if (ticketOpen) startPolling(); }
  function closePanel() { panel.hidden = true; button.setAttribute("aria-expanded", "false"); stopPolling(); }
  button.setAttribute("aria-expanded", "false"); button.addEventListener("click", function () { if (panel.hidden) open(); else closePanel(); }); close.addEventListener("click", closePanel); composer.addEventListener("submit", submit); input.addEventListener("keydown", function (event) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); composer.requestSubmit(); } });
}());
